### ISSUE TITLE
Link sql

### ISSUE THREAD

**Issue by hoang3402** [Yersin-K18/BookLibraryAPI#10]
Key word: .net core db first

Info database:
name: yersin_db
host: sql.bsite.net\MSSQL2016
username: yersin_db
pass: k8eHarwdXQH.AJg

làm xong thì chụp ảnh

**Comment by vule2303** [comment]
![image](https://github.com/Yersin-K18/BookLibraryAPI/assets/107258990/7ca04c6c-4e74-4a8a-a4d6-efa827e7db86)

**Comment by vule2303** [comment]
phải không hoàng ơi

**Comment by vule2303** [comment]
![image](https://github.com/Yersin-K18/BookLibraryAPI/assets/107258990/f8466ad2-b8aa-4364-b969-f6e408dacfbc)
lỗi xác thực m ơi

**Comment by vule2303** [comment]
xem lại sever có đúng k z

**Comment by hoang3402** [comment]
server đúng
![image](https://github.com/Yersin-K18/BookLibraryAPI/assets/54090585/74053149-a42f-4aa2-a0bd-06c5d5dd4bea)
